# Generated by Django 6.0.1 on 2026-03-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='heaad_of_dept',
            new_name='head_of_dept',
        ),
    ]
