# Generated by Django 6.0.1 on 2026-07-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_student_profile_pic_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='students/profiles/'),
        ),
    ]
